[package]
name = "advent2023"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["day_01", "day_02", "day_03", "day_04"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
regex = "1.10.2"
